{% set name = "eegrasp" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: 0.0.4

source:
  url: https://pypi.io/packages/source/p/pygsp2/pygsp2-0.0.4.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - hatchling
    - pip
  run:
    - python >=3.11
    - scipy
    - numpy
    - mne
    - matplotlib-base
    - pygsp2
    - tqdm
    - joblib
    - pylint
    - pandas

test:
  imports:
    - eegrasp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gsp-eeg/EEGrasp
  summary: Package for EEG Graph signal Processing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lcortesg
